- hosts: datanode
  vars_prompt:
          - name: directoryname
            prompt: Please Enter the Directory name for datanode
            private: no
          - name: masterip
            prompt: Please enter the master node IP
            private: no
  tasks:
          - name: Downloading Jdk software
            get_url:
              url: http://35.244.242.82/yum/java/el7/x86_64/jdk-8u171-linux-x64.rpm
              dest: /root
            register: Jdk_Download_status

          - name: Downloading hadoop software
            get_url:
              url: https://archive.apache.org/dist/hadoop/core/hadoop-1.2.1/hadoop-1.2.1-1.x86_64.rpm
              dest: /root
            register: hadoop_download_status

          - name: Install Jdk software
            command: rpm -i jdk-8u171-linux-x64.rpm
            when: Jdk_download_status.failed == false
            register: jdk_status

          - name: Install Hadoop software
            command: rpm -i hadoop-1.2.1-1.x86_64.rpm --force
            when: hadoop_download_status.failed == false
            register: hadoop_status
         
          - name: Deleting the core site and hdfs site file
            command: rm -rf /etc/hadoop/core-site.xml  /etc/hadoop/hdfs-site.xml
            register: hadoop_conf_file_remove_status

          - name: Copying core file using template
            template:
              src: /root/datanode/core-site.xml
              dest: /etc/hadoop
            register: conf_file_copy_status

          - name: Creating Directory for datanode
            file:
              path: /{{ directoryname }}
              state: directory
            register: directory_status

          - name: Copying hdfs file using template
            template:
              src: /roo/datanode/hdfs-site.xml
              dest: /etc/hadoop
            when: directory_status.failed == false

          - name: Formatting hadoop datanode
            shell: hadoop datanode -format
            ignore_errors: true

          - name: starting datanode service
            command: hadoop-daemon.sh start datanode
            
          
          - name: Making the service permanent
            shell: echo "hadoop-daemon.sh start datanode" >> /root/.bashrc

          - name: Playbook status
            debug:
               msg: "Data node configure successfully"  
